### ISSUE TITLE
Inaccurate documentation: use of CMAKE_MODULE_PATH during inclusion

### ISSUE THREAD

**Issue by pthedinger** [compor/llvm-ir-cmake-utils#17]
The documentation says:

- In your CMakeLists.txt file include(LLVMIRUtil.cmake).

However, CMake doesn't search your CMAKE_MODULE_PATH in that case and so that doesn't work very well.

As per the examples, it should simply be:

- In your CMakeLists.txt file include(LLVMIRUtil).

**Comment by compor** [comment]
Hello there and thanks for filing this issue.
Let me have a look and I'll get back to you.

**Comment by compor** [comment]
@pthedinger I can confirm this mistake. Thanks for catching this.

**Comment by compor** [comment]
Fixed by commit 6a956a411ba157f2ceccf07a85f744eb2455e8c3.
