### ISSUE TITLE
CMake configuration error

### ISSUE THREAD

**Issue by juanfgarcia** [compor/llvm-ir-cmake-utils#19]
I'm getting this error when I try to ``cmake ..``:

-- Configuring incomplete, errors occurred! 
See also "[...]/CMakeFiles/CMakeOutput.log".

Without the include(LLVMIRUitls) does not appear

**Comment by compor** [comment]
Hello there,

Thanks for reporting this.

However, I need some more detail:

- What is your version of CMake?
- A minimal CMakeLists.txt that reproduces this error.
- What's in that error log (CMakeOutput.log)?

Cheers,
Chris

**Comment by juanfgarcia** [comment]
My version 3.10.2

This error can be reproduced only with the include
``
project(CFECORE C)

list(APPEND CMAKE_MODULE_PATH "${CMAKE_CURRENT_SOURCE_DIR}/cmake")
include(llvm-ir-cmake-utils)
``
In the CMakeOutput.log there doesn't seem to be any error log

[CMakeOutput.log](https://github.com/compor/llvm-ir-cmake-utils/files/5581546/CMakeOutput.log)

**Comment by compor** [comment]
As the example (under `examples/`) show you need to add the `cmake` dir of this module in the modules path (`CMAKE_MODULE_PATH`).

So, this means for you

```
list(APPEND CMAKE_MODULE_PATH "${CMAKE_CURRENT_SOURCE_DIR}/../cmake/llvm-ir-cmake-utils/cmake/")
```

Can you please try this and let me know?

I thought this was fairly obvious, but apparently not. I'll update the documentation.

**Comment by juanfgarcia** [comment]
I was trying with the LLVMIRUtils.cmake directly inside of my cmake directory. I cloned the full llvm-ir-cmake-utils in my cmake directory and tried this line and I got the same output.

**Comment by juanfgarcia** [comment]
I found the problem, it was missing the line:

```
cmake_minimum_required(VERSION 3.10)
```

Thank you so much for your help

**Comment by compor** [comment]
Oh well, we would have found it the minimal `CMakeLists.txt` was provided as I asked initially.
Glad it's resolved.
