### ISSUE TITLE
How to support px4 compilation?

### ISSUE THREAD

**Issue by Lqs66** [compor/llvm-ir-cmake-utils#31]
hello, I'm trying to generate llvm IR in px4 compilation using your tool, I imported cmake as you requested and added include to CMakeLists.txt, during cmake I see the console output - LLVM IR Utils. finally I run make to compile but it doesn't work until I don't see IR until the binary is generated. Does your tool support px4 compilation?

**Comment by compor** [comment]
Hello @Lqs66,

I'm not familiar px4; does it use llvm/clang? what is the source language?

Internally, `llvm-ir-cmake-utils` depend on the source language as required by cmake to generate LLVM IR.
You can see this roughly [here][1].

If the px4 compilation uses something custom, then maybe you can override those, but for CMake, it needs to be able to detect the [`LINKER_LANGUAGE`][2].


[1]: https://github.com/compor/llvm-ir-cmake-utils/blob/082bfe772dca6e6ab05614f48357774ef2ebf4d8/cmake/LLVMIRUtilInternal.cmake#L23
[2]: https://cmake.org/cmake/help/latest/prop_tgt/LINKER_LANGUAGE.html
