### ISSUE TITLE
Example 3: No bytecode generation

### ISSUE THREAD

**Issue by nbruns1** [compor/llvm-ir-cmake-utils#33]
Is it intentional that Example 3 does not generate bytecode?

> root@d590c2e5d6fb:/opt/src/example03/build# tree
.
|-- CMakeCache.txt
|-- CMakeFiles
|   |-- 3.26.4
|   |   |-- CMakeCCompiler.cmake
|   |   |-- CMakeCXXCompiler.cmake
|   |   |-- CMakeDetermineCompilerABI_C.bin
|   |   |-- CMakeDetermineCompilerABI_CXX.bin
|   |   |-- CMakeSystem.cmake
|   |   |-- CompilerIdC
|   |   |   |-- CMakeCCompilerId.c
|   |   |   |-- a.out
|   |   |   `-- tmp
|   |   `-- CompilerIdCXX
|   |       |-- CMakeCXXCompilerId.cpp
|   |       |-- a.out
|   |       `-- tmp
|   |-- CMakeConfigureLog.yaml
|   |-- CMakeDirectoryInformation.cmake
|   |-- CMakeRuleHashes.txt
|   |-- CMakeScratch
|   |-- Makefile.cmake
|   |-- Makefile2
|   |-- TargetDirectories.txt
|   |-- cmake.check_cache
|   |-- pkgRedirects
|   `-- progress.marks
|-- Makefile
|-- cmake_install.cmake
`-- src
    |-- CMakeFiles
    |   |-- CMakeDirectoryInformation.cmake
    |   |-- bar.dir
    |   |   |-- DependInfo.cmake
    |   |   |-- bar.cpp.o
    |   |   |-- bar.cpp.o.d
    |   |   |-- build.make
    |   |   |-- cmake_clean.cmake
    |   |   |-- cmake_clean_target.cmake
    |   |   |-- compiler_depend.make
    |   |   |-- compiler_depend.ts
    |   |   |-- depend.make
    |   |   |-- flags.make
    |   |   |-- link.txt
    |   |   `-- progress.make
    |   |-- bar_as.dir
    |   |   |-- DependInfo.cmake
    |   |   |-- build.make
    |   |   |-- cmake_clean.cmake
    |   |   |-- compiler_depend.make
    |   |   |-- compiler_depend.ts
    |   |   `-- progress.make
    |   |-- bar_bc.dir
    |   |   |-- DependInfo.cmake
    |   |   |-- build.make
    |   |   |-- cmake_clean.cmake
    |   |   |-- compiler_depend.make
    |   |   |-- compiler_depend.ts
    |   |   `-- progress.make
    |   |-- bar_bc_lib.dir
    |   |   |-- DependInfo.cmake
    |   |   |-- build.make
    |   |   |-- cmake_clean.cmake
    |   |   |-- compiler_depend.make
    |   |   |-- compiler_depend.ts
    |   |   |-- depend.make
    |   |   |-- flags.make
    |   |   |-- link.txt
    |   |   `-- progress.make
    |   |-- bar_dis.dir
    |   |   |-- DependInfo.cmake
    |   |   |-- build.make
    |   |   |-- cmake_clean.cmake
    |   |   |-- compiler_depend.make
    |   |   |-- compiler_depend.ts
    |   |   `-- progress.make
    |   |-- bar_llvmlink.dir
    |   |   |-- DependInfo.cmake
    |   |   |-- build.make
    |   |   |-- cmake_clean.cmake
    |   |   |-- compiler_depend.make
    |   |   |-- compiler_depend.ts
    |   |   `-- progress.make
    |   |-- bar_pass1.dir
    |   |   |-- DependInfo.cmake
    |   |   |-- build.make
    |   |   |-- cmake_clean.cmake
    |   |   |-- compiler_depend.make
    |   |   |-- compiler_depend.ts
    |   |   `-- progress.make
    |   |-- bar_pass2.dir
    |   |   |-- DependInfo.cmake
    |   |   |-- build.make
    |   |   |-- cmake_clean.cmake
    |   |   |-- compiler_depend.make
    |   |   |-- compiler_depend.ts
    |   |   `-- progress.make
    |   |-- bar_pass3.dir
    |   |   |-- DependInfo.cmake
    |   |   |-- build.make
    |   |   |-- cmake_clean.cmake
    |   |   |-- compiler_depend.make
    |   |   |-- compiler_depend.ts
    |   |   `-- progress.make
    |   |-- bar_pass4.dir
    |   |   |-- DependInfo.cmake
    |   |   |-- build.make
    |   |   |-- cmake_clean.cmake
    |   |   |-- compiler_depend.make
    |   |   |-- compiler_depend.ts
    |   |   `-- progress.make
    |   `-- progress.marks
    |-- Makefile
    |-- cmake_install.cmake
    |-- libbar.a
    `-- llvm-ir
        |-- bar_as
        |-- bar_bc
        |-- bar_bc_lib
        |-- bar_dis
        |-- bar_llvmlink
        |-- bar_pass1
        |-- bar_pass2
        |-- bar_pass3
        `-- bar_pass4

**Comment by compor** [comment]
Hmm, let me have a look.
How did you configure/build this?

**Comment by nbruns1** [comment]
Sorry, the error was at my side. Thank you for your effort!
