### ISSUE TITLE
use cmake generate expression to simplify some jobs

### ISSUE THREAD

**Issue by WuTUT** [compor/llvm-ir-cmake-utils#37]
I think there is a simple way to implement these functions
- llvmir_extract_compile_defs_properties
- llvmir_extract_include_dirs_properties
- llvmir_extract_compile_flags
- llvmir_extract_compile_option_properties

if use cmake [generate expressions ](https://cmake.org/cmake/help/latest/manual/cmake-generator-expressions.7.html#id2:~:text=Using%20variables%20to%20build%20up%20a%20more%20complex%20generator%20expression%20is%20also%20a%20good%20way%20to%20reduce%20errors%20and%20improve%20readability.%20The%20above%20example%20can%20be%20improved%20further%20like%20so%3A),  each function will be only one line.
```cmake
  set(CMD_ARGS "-emit-llvm" ${IN_STANDARD_FLAGS} ${IN_LANG_FLAGS})
  add_custom_command(OUTPUT ${FULL_OUT_LLVMIR_FILE}
    COMMAND ${LLVMIR_COMPILER} ${CMD_ARGS}
    "$<JOIN:$<TARGET_PROPERTY:${DEPENDS_TRGT},COMPILE_OPTIONS>,;>"
    "$<JOIN:$<TARGET_PROPERTY:${DEPENDS_TRGT},COMPILE_FLAGS>,;>"
    "-D$<JOIN:$<TARGET_PROPERTY:${DEPENDS_TRGT},COMPILE_DEFINITIONS>,;-D>"
    "-I$<JOIN:$<TARGET_PROPERTY:${DEPENDS_TRGT},INCLUDE_DIRECTORIES>,;-I>"
    -c ${ABS_IN_FILE} -o ${FULL_OUT_LLVMIR_FILE}
    DEPENDS ${ABS_IN_FILE}
    IMPLICIT_DEPENDS ${LINKER_LANGUAGE} ${ABS_IN_FILE}
    COMMENT "Generating LLVM bitcode ${OUT_LLVMIR_FILE}"
    COMMAND_EXPAND_LISTS
    VERBATIM)
```

In addition, there is an important benefit: there is no need to recursively fetch the include directories introduced by target_link_library. For instance, if a library is linked publicly, its interface headers will also be visible. I test in my complicated project and it finds all include paths correctly.

The drawback may be the dependency on a higher version of CMake. However, I haven't tested whether this code works on cmake-version 3.0.

**Comment by compor** [comment]
Hi there, the support for generator expressions has evolved since before v3.0.
As far as I know, things like `TARGET_PROPERTY` do not exist in version 3.0 and I'd like to keep this as widely available as possible.

Speed was never a concern.
